[project]
name = "code-execution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "morphcloud>=0.1.32",
    "pyright>=1.1.398",
    "ruff>=0.11.2",
]
